=== anikom15/presetgen/pipelines/pipeline.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Pipeline",
  "type": "object",
  "properties": {
    "root_path": { "type": "string" },
    "shaders": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": { "type": "string" }
    },
    "textures": {
      "type": "array",
      "items": { "type": "string" },
      "minItems": 1
    },
    "options": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "filter_linear": { "type": "boolean" },
          "mipmap_input": { "type": "boolean" },
          "wrap_mode" : { "type": "string", "enum": ["clamp_to_edge", "clamp_to_border", "repeat", "mirrored_repeat"] },
          "scale_type": {
            "type": "array",
            "items": { "type": "string", "enum": ["absolute", "source", "viewport"] },
            "minItems": 1,
            "maxItems": 2
          },
          "scale": {
            "type": "array",
            "items": { "type": "number" },
            "minItems": 1,
            "maxItems": 2
          }
        },
        "additionalProperties": true
      }
    },
    "texture_options": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "linear": { "type": "boolean" },
          "mipmap": { "type": "boolean" },
          "wrap_mode" : { "type": "string", "enum": ["clamp_to_edge", "clamp_to_border", "repeat", "mirrored_repeat"] }
        },
        "additionalProperties": true
      }
    },
    "parameters": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "required": [
    "root_path",
    "shaders"
  ],
  "additionalProperties": true
}

=== anikom15/presetgen/pipelines/misc/post.json
{
    "root_path" : "../../../shaders",
    "shaders" : {
        "color" : "color-sdr",
        "bezel" : "bezel-sdr"
    },
    "textures" : [
        "BORDER"
    ],
    "options" : {
        "bezel": {
            "filter_linear" : true,
            "scale_type" : ["viewport"]
        }
    },
    "texture_options" : {
        "BORDER": {
            "linear": true,
            "mipmap": true,
            "wrap_mode": "clamp_to_edge"
        }
    }
}
